debug: false
logging.config: classpath:logback-spring.xml


spring:
  profiles:
    active: @env@
  messages:
    basename: languages/messages
    cache-duration: -1
  servlet:
    multipart:
      enabled: true
      max-file-size: 40960
      max-request-size: 20971520
  devtools:
    restart:
      enabled: true



mybatis-plus:
  mapper-locations: classpath*:mybatis/sqlMap/**/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml
  global-config:
    db-config:
      id-type: ASSIGN_UUID
      logic-delete-field: isDel  # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)