spring:
  main:
    allow-circular-references: true
  profiles:
    active: @env@
  messages:
    basename: languages/messages
    cache-duration: -1
  servlet:
    multipart:
      enabled: true
      max-file-size: 40960
      max-request-size: 20971520
  devtools:
    restart:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 30s
  #
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlite:${logging.file.path}/trade.db
    username:
    password:
    hikari: #Springboot2.0以后默认数据库连接池选择了Hikari（性能高）
      pool-name: Retail_HikariCP
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 600000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1

mybatis-plus:
  mapper-locations: classpath*:mybatis/sqlMap/**/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml
  global-config:
    db-config:
      id-type: ASSIGN_UUID
      logic-delete-field: isDel  # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)