#---------------------------       dev       ------------------------------------------------
server:
  port: 8080
  servlet:
    context-path: /trade_c2c_celo
    session:
      timeout: P0DT0H0M300.0S #300秒，必须是合法的Duration
  tomcat:
    basedir: d:/log/tomcat
    accesslog:
      enabled: true
      suffix: .log
      prefix: access_log
      file-date-format: .yyyy-MM-dd
      directory: logs
      pattern: common
#配置tomcat内部日志的级别
logging.level:
  org.apache.tomcat: INFO
  org.apache.catalina: INFO

#余额文件的路径
log.path: d:/log${server.servlet.context-path} #不能以斜杠结尾
balanceFilePath: ${log.path}/balance.txt

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlite:${log.path}/trade.db
    username:
    password:
    hikari: #Springboot2.0以后默认数据库连接池选择了Hikari（性能高）
      pool-name: Retail_HikariCP
      minimum-idle: 5 #最小空闲连接数量
      idle-timeout: 600000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1

properties.location: classpath:application-dev.yml

chat.maxHistory:  3

trade:
  core.package: com.liujun.trade_ff.core
  goods: celo #交易哪种商品。大小写随意，由各平台对应的trade类负责转换
  money: usd #用哪种货币完成交易。大小写随意，由各平台对应的trade类负责转换
  formatGoodsStr: "0.000000"
  formatMoneyStr: "0.000"
  earnMoney: true #赚取什么？钱还是货?如果赚钱，那么系统会保证货物数量保持不变
  minCoinNum: 0.1 #买卖币时，最小交易金额。如果是合约，最少买一手
  moneyPrice: 6.9 #计价货币值多少人民币，用来把利润估算成人民币
  marketOrderSize: 100 #获取市场深度时，买单、卖单分别获取多少个？【对okcoin有效,chbtc固定是50】
  orderStepLength: 0.02 #查询市场挂单时， 按价格合并订单，例如：0.1或0.001(只保留一位有效数字,例如0.03。不能是0.123456，) 比特币价格高，太小的差距显得没有意义。建议为万一到万五.
  #交易一次(不包含"调节商品数量"等特殊交易)，最少要赚多少【人民币】？如果扣除了各种成本，那么一毛钱也值得赚。亏损频率越高，atLeastEarn就应该越高。
  # 请不要考虑矿工费，因为maxEarnCost.earn已经减去了矿工费。这里应该拍脑袋决定
  atLeastEarn: 0.1
  #最低利润率(差价除以价格)，跟滑点有关：因为uniswap上面建议的滑点是0.05%,比原链超导兑换建议1%
  atLeastRate: 0.001
  positionRate: 1 #仓位上限，占余额的比例。0.5表示50%，那么下跌2/3时爆仓。1表示100%，那么下跌50%时爆仓

engine:
  time_queryOrder: 3 #间隔多少【秒】查询一次市场挂单. 请用3、6、9、12等等
  time_oneCycle: 30 #每循环一次，最大允许占用多少【秒】.dex执行一次可能要30秒，那么这期间这个系统都被阻塞
  time_sleep: 1000 #每次对平台进行写操作后，休眠多少【毫秒】
  waitSecondAfterException: 3 #如果抛出异常，暂停多少【秒】
  trade_model: simple #采取哪种模式匹配订单？simple, exact
  time_beginBalance: 0 #每天几点开始记录余额【单位：小时】
  time_waitBalance: 6 #间隔多久,记录余额？ 【单位：小时】

######################       平台相关的配置            #########################################
#-------------okcoin-------------------------------
okcoin:
  goods:  #交易哪种商品。大小写随意，由各平台对应的trade类负责转换
  money:  #用哪种货币完成交易。大小写随意，由各平台对应的trade类负责转换
  apiKey: ca8023da-f3c7-4ee9-8ec7-b9fb6f052a18
  secretKey: 28D1AC3119031BE2377A4D2A810DD3E4
  url: https://www.okex.com
  passphrase: liujun924586
  feeRate: 0.0015

okcoinF: #期货标的
  goods:  #交易哪种商品。大小写随意，由各平台对应的trade类负责转换
  money:  #用哪种货币完成交易。大小写随意，由各平台对应的trade类负责转换
  underlying: BTC-USD
  alias: quarter #期货类别。本周 this_week  次周 next_week  季度 quarter  次季度 bi_quarter
  feeRate: 0.0005
okcoinF2.alias: bi_quarter

#---------  bitfinex liujun2
bitfinex.apiKey: ZiPkmu74WueMT8Ewo0ckRt8MBU9QIRH44AeajOc6Vfa
bitfinex.secretKey: Os8W2NBsOknX86zdwwZMeY9KmimzsPPP1TJBwRsH5Fn
#------------huobi -----------------
huobi.apiKey: vfd5ghr532-b7b99598-fb760722-98117
huobi.secretKey: 0d4d0ced-221743d0-d83b34d6-952d1
huobi.feeRate: 0.002
huobi.url: https://api.huobi.com
#------------poloniex-----------------------  https://poloniex.com/support/api/    https://github.com/TheCookieLab/poloniex-api-java
poloniex.apiKey: 2T6JBKDG-QKWFZK6R-8L9P74W0-LHFC7ILZ
poloniex.secretKey: a620d6783c2e8d806f8c1b3254d0c73a03f7efe75466f08e6cc96212200610ad651c73a3722e340c409f0a8741741b519305a5f3defd3832aedb10e47bf39f4c
# ---------  binance  ------
binance:
  goods: celo #交易哪种商品。大小写随意，由各平台对应的trade类负责转换
  money: busd #用哪种货币完成交易。大小写随意，由各平台对应的trade类负责转换
  apiKey: 1mAOQOu33xJixjS2yI7BpT1w0QsVCKPdLYS5RbQOYBPDuug5VxQXnWtmOe0FjhsA
  secretKey: 8StAUYBofm79mKfil9rRTgwePOKGMVYvSH4bnUJHCXbL9qW7qlYLxzWNCFlneX2W
  feeRate: 0.001
  url: https://api.binance.com
#合约交易，币本位
binanceF:
  goods:  #交易哪种商品。大小写随意，由各平台对应的trade类负责转换
  money:  #用哪种货币完成交易。大小写随意，由各平台对应的trade类负责转换
  url: https://dapi.binance.com
  feeRate: 0.0004
  #合约类型：本季：CURRENT_QUARTER， 下季：NEXT_QUARTER， 永续合约：PERPETUAL
  contractType: CURRENT_QUARTER

#-------------uniswap-------------------------------gas limit: 162773，实际使用：122694，总共0.009325eth
#矿工费21元人民币。要求利润大于这个数，才能交易。
#dex执行一次可能要30秒，那么这期间这个系统都被阻塞
uniswap:
  naitveToken: celo #链的原生币，大小写都行。也是gas消耗的币的名称。因为uniswap能用在多个区块链
  goods: celo #交易哪种商品。大小写随意，由各平台对应的trade类负责转换
  money: cusd #用哪种货币完成交易。大小写随意，由各平台对应的trade类负责转换
  url: http://127.0.0.1:8090
  ethAddress: "0xB0d1435590B4f14A5f4414f93489945546162ffc"
  feeRate: 0.003 #uniswap平台的交易手续费是多少？不同币种，手续费不一样，wbtc是0.3%或0.05%，稳定币兑换是0.01%. celo-cusd是0.3%
  gasPercent: 1.0 #强制调高gas价格，对矿工费进行悲观的估算.